<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Customer::factory()->count(10)->create();
        $clients =
            [
                [
                    'name' => 'Salvador Construções Lda',
                    'company_name' => 'Salvador Construções Lda',
                    'email' => 'info@salvadorconstrucoes.co.mz',
                    'mobile' => '+258875888887',
                    'phone' => '+258844303366',
                    'address' => 'São Dámaso, Q.98B, N° 123, Cidade da Matola',
                    'city' => 'Matola',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => 'https://salvadorconstrucoes.co.mz',
                    'country' => 'Moçambique',
                    'notes' => 'Empresa de construção de Moçambique, que atua em diversas áreas, como infraestruturas públicas, engenharia civil, instalações técnicas e reabilitação de edifícios. Já completou mais de 100 projetos e foi premiada em mais de duas ocasiões.',
                    'client_type' => 'company',
                ],

                [
                    'name' => 'Construsoyo Moçambique, Lda',
                    'company_name' => 'Construsoyo Moçambique, Lda',
                    'email' => 'info@construsoyo.co.mz',
                    'mobile' => '+258849633070',
                    'phone' => '+258845661410',
                    'phone' => '845661410',
                    'website' => '',
                    'address' => 'Sommerchild II - Rua das Rosa nr 306',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'country' => 'Moçambique',
                    'notes' => 'Empresa de construção civil e obras públicas. Possui Alvará de Construção de Classe 7.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Talho tonko',
                    'company_name' => 'Talho tonko',
                    'email' => 'pauldecastro1@gmail.com',
                    'mobile' => '+258849022970',
                    'phone' => '',
                    'address' => '35 Jaquim Chissano Matola A (Junto paragem Bic), Matola',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => 'http://talhotonko.com',
                    'country' => 'Moçambique',
                    'notes' => 'Talho com mais de 5 anos dinamizando o bem servir naquela que é uma das tarefas principais de quem comercializa carne. . . Seleccionar do melhor para si!
Pode encontrar diversos tipos de carne e de boa qualidade, assim encontra aqui do melhor e de primeira sem precisar escolher muito, pois nós já a seleccionamos para si.
Comercializamos também derivados poupando o seu tempo e oferecendo a opção de encontrar tudo num só lugar.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Talho tonko - fabrica',
                    'company_name' => 'Talho tonko  - fabrica',
                    'email' => 'pauldecastro1@gmail.com',
                    'mobile' => '+258873188295',
                    'phone' => '+258863865892',
                    'address' => '35 Jaquim Chissano Matola A (Junto paragem Bic), Matola',
                    'city' => 'Matola',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => 'http://talhotonko.com',
                    'country' => 'Moçambique',
                    'notes' => 'Talho com mais de 5 anos dinamizando o bem servir naquela que é uma das tarefas principais de quem comercializa carne. . . Seleccionar do melhor para si!
Pode encontrar diversos tipos de carne e de boa qualidade, assim encontra aqui do melhor e de primeira sem precisar escolher muito, pois nós já a seleccionamos para si.
Comercializamos também derivados poupando o seu tempo e oferecendo a opção de encontrar tudo num só lugar.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Pakai imobiliario',
                    'company_name' => 'Pakai imobiliario',
                    'email' => null,
                    'mobile' => '+258848468135',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Gravita Mozambique LDA',
                    'company_name' => 'Gravita Mozambique LDA',
                    'email' => 'cm@gravitamozambique.com',
                    'mobile' => '+258841163513',
                    'phone' => '+258-858046802',
                    'address' => 'Av. Samora Machel, No 672-EN4, Bairro Matola-Gare, Tchumene-2',
                    'city' => 'Matola',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => 'https://www.gravitaindia.com/geographies/mozambique',
                    'country' => 'Moçambique',
                    'notes' => 'Empresa de reciclagem de baterias, alumínio e plástico.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Rodway',
                    'company_name' => 'Rodway',
                    'email' => null,
                    'mobile' => '+258845379943',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Garagem Estrela, Lda',
                    'company_name' => 'Garagem Estrela, Lda',
                    'email' => 'garagemestrela@gmail.com',
                    'mobile' => '+258862986419',
                    'phone' => '+258847183096',
                    'address' => 'Av. Da Namaacha, Parcela nº 492, 1 9 e 492, Maputo 1100',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => 'Uma oficina de serviços e reparação de automóveis em Moçambique, conhecida por oferecer uma variedade de serviços de manutenção de veículos.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Well Wash',
                    'company_name' => 'Well Wash',
                    'email' => 'well.wash@hotmail.com',
                    'mobile' => '+258847225723',
                    'phone' => '+258842478055',
                    'address' => '1660 Avenida de Maguiguana, Maputo',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => null, // Não foi encontrado um site oficial.
                    'country' => 'Moçambique',
                    'notes' => 'Lavandaria de viaturas. Focada em serviços de lavagem de carros, possivelmente com uma abordagem ecológica.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'TCR',
                    'company_name' => 'TCR',
                    'email' => null,
                    'mobile' => '+258870898598',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Signo construções',
                    'company_name' => 'Signo construções',
                    'email' => null,
                    'mobile' => '+258873030675',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'GOP Construções',
                    'company_name' => 'GOP Construções',
                    'email' => null,
                    'mobile' => '+258867736676',
                    'phone' => '+258847736676',
                    'phone' => '84736676',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Moz Furos',
                    'company_name' => 'Moz Furos',
                    'email' => 'mozfuros@gmail.com',
                    'mobile' => '+258827273920',
                    'phone' => '+258846263476',
                    'address' => 'Av 24 Julho N4235 R/C , Maputo, Mozambique',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => null,
                    'country' => 'Moçambique',
                    'notes' => 'Empresa provavelmente especializada na perfuração de furos de água em Moçambique.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'John Block',
                    'company_name' => 'John Block',
                    'email' => null,
                    'mobile' => '+258845709597',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Atlanta cosméticos Lda',
                    'company_name' => 'Atlanta cosméticos Lda',
                    'email' => 'alfiadochissume25@gmail.com',
                    'mobile' => '+258847384276',
                    'phone' => '',
                    'address' => 'Av. Moçambique 1522',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Moz Plast',
                    'company_name' => 'Moz Plast',
                    'email' => 'intermetal@me.com',
                    'mobile' => '+258847315027',
                    'phone' => '+258844673367',
                    'address' => 'Avenida Dos Trabladores No.888, Nampula, Mozambique',
                    'city' => 'Nampula',
                    'province' => 'Nampula',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => 'Fabricantes especializados em tubos plásticos duráveis e resistentes, ideais para construções, irrigação, redes hidráulicas e muito mais!',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Absolute Power',
                    'company_name' => 'Absolute Power Lda',
                    'email' => 'info@absolutepowermoz.com',
                    'mobile' => '+258871319280', // Mantido com base na informação fornecida, mas é importante verificar se ainda está ativo.
                    'phone' => '+258841902850',
                    'address' => 'Avenida 24 de Julho, 3358, Bairro da Polana Caniço A',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => 'https://absolutepowermoz.com/',
                    'country' => 'Moçambique',
                    'notes' => 'Especializada em soluções de energia, incluindo sistemas de energia solar, geradores e instalações elétricas.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Martifer Visaboinas',
                    'company_name' => 'Martins Visalinas',
                    'email' => null,
                    'mobile' => '+2588843149240',
                    'phone' => '+258878987380',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Corsil',
                    'company_name' => 'Corsil',
                    'email' => null,
                    'mobile' => '+258874000123',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Car moc',
                    'company_name' => 'Car moc',
                    'email' => 'null',
                    'mobile' => '+258844461285',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Plano Digital',
                    'company_name' => 'Plano Digital',
                    'email' => null,
                    'mobile' => '+258847916781',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Auto mano',
                    'company_name' => 'Auto mano',
                    'email' => null,
                    'mobile' => '+258845221078',
                    'phone' => '',
                    'address' => null,
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => null,
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Arz Construction, Lda ',
                    'company_name' => 'Arz Construction, Lda ',
                    'email' => 'arzconstructionlda@gmail.com',
                    'mobile' => '+258846985451',
                    'phone' => null,
                    'address' => 'nr 420 Avenida Paulo Samuel Kankhomba, Maputo',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => null,
                    'country' => 'Moçambique',
                    'notes' => 'Empresa de construção civil que atuou na construção do edifício A Flora em Maputo.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'ELC Transportes e Serviços',
                    'company_name' => 'ELC Transportes e Serviços',
                    'email' => null,
                    'mobile' => '+258877505963',
                    'phone' => '+258848105984',
                    'address' => 'Bairro Malhampsene, n45, 2 andar Matola, Maputo 1114, Mozambique',
                    'city' => 'Matola',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => 'ELC Transportes e Serviços is based in Mozambique and address is: Bairro Malhampsene, n45, 2 andar Matola, Maputo 1114, Mozambique',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Condo Construções',
                    'company_name' => 'Condo Construções',
                    'email' => null,
                    'mobile' => '+258840487149',
                    'phone' => '',
                    'address' => 'Rua R Jardim 204, Maputo',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'website' => '',
                    'country' => 'Moçambique',
                    'notes' => 'A empresa Condo Construções é uma construtora civil localizada na cidade de Maputo, Moçambique. Embora não haja um site oficial disponível, a empresa aparece em perfis profissionais como o LinkedIn indicando sua atividade na área de construção civil com base em Maputo.',
                    'client_type' => 'company',
                ],
                [
                    'name' => 'Turbomar',
                    'company_name' => 'Turbomar',
                    'email' => 'administrativo@turbomar.co.mz',
                    'mobile' => '+258845301115',
                    'phone' => '',
                    'address' => '1547 Avenida Do Trabalho, Maputo, Moçambique',
                    'city' => 'Maputo',
                    'province' => 'Maputo',
                    'postal_code' => '1100',
                    'country' => 'Moçambique',
                    'website' => 'http://www.turbomar.co.mz',
                    'notes' => "A Turbomar Moçambique é uma empresa que pertence ao Grupo Turbomar, grupo empresarial português de cariz familiar e com mais de 60 anos de actividade no sector de equipamentos industriais.
O Core-Business da Turbomar Moçambique está focado na venda, assistência e aluguer de grupos geradores e equipamentos de movimentação de cargas, representado em exclusividade a marca italiana Pramac para o território Moçambicano.
Dispõe de uma equipa técnico-comercial de elevado know-how e amplamente reconhecida no sector.
A sua sede está localizada na Cidade Maputo Av. Trabalho 1547 R/C que apresenta as características ideais para a actividade desenvolvida.",
                    'client_type' => 'company',
                ],
            ];

        foreach ($clients as $client) {
            Customer::create($client);
        }
    }
}
